### ISSUE TITLE
Vehicle select screen cars are piling up.

### ISSUE THREAD

**Issue by mvolpa1** [RinglingGameArt/2014-Racing-Game#479]
When I was just pushing the arrow key to get to my car the broken cars piled up, and the upcoming cars will keep pileing up.
![select screen error](https://cloud.githubusercontent.com/assets/7010880/2537438/97e02ba2-b5b0-11e3-924e-9fa822c4467e.jpg)

**Comment by egingric** [comment]
I think I fixed it. Please test and let me know!

**Comment by mvolpa1** [comment]
I'm able to spawn the cars and have them not drop, but it took awhile to get it to happen, and the I only achieved it twice.  I think the timing is to hard for anyone to get.  Are you adding the names to the cars so we know who made what?

![capture](https://cloud.githubusercontent.com/assets/7010880/2675785/aff1a670-c123-11e3-8607-4fa2dff6ec93.JPG)

**Comment by egingric** [comment]
That is probably a specific car that is not dropping. Please press B to switch to best of Ringling Mode so that only cars that actually work are in there. Then let me know if you can still break it. Thanks for you help in testing this!

I want to add names soon, but due to priorities and safety concerns there is probably not enough time to add that feature today.

**Comment by mvolpa1** [comment]
This was with the best of Ringling cars.

**Comment by egingric** [comment]
Uh oh. How do I reproduce it the bug?

**Comment by mvolpa1** [comment]
I think if you go any direction (left or right) at a medium speed, but get it so the cars are not dropping down.  Sometimes I would alternate directions, I don't know if this caused it because I wouldn't check to see if it was broken when I changed direction, I only got it working by going periods over 30 seconds.
