### ISSUE TITLE
Lap Timer Problem

### ISSUE THREAD

**Issue by egingric** [RinglingGameArt/2014-Racing-Game#611]
My first lap was 2:24 and my second lap was 1:24. I was driving about the same. Why is that?

**Comment by cpavlovs** [comment]
I"m not quite sure why that is happening? I noticed that the timer starts during the intro sequence so that's adding some time to the first lap, but certainly not a full minute. I played my level a few times just now and managed to get about the same times on both playthroughs. I will move back the playerstart so the timer does not start immediately but I will keep trying to test why the timer might be screwing up.

**Comment by egingric** [comment]
That was probably it. I didn't realize the counter had started. It is not supposed to start until you cross the start finish line.
