### ISSUE TITLE
Car exploded, Player remained

### ISSUE THREAD

**Issue by Kjohnso1** [RinglingGameArt/2014-Racing-Game#63]
The pixar lamp looking things blew up the vehicle, but didn't kill the player so there was no respawn.

**Comment by egallaha** [comment]
I got a ticket like this earlier, and sorry about that. The damage is intentional but the failed screen isn't. The balls are supposed to instantly kill you because they are easy to avoid.

As for not killing the player, you need to press "e" to respawn and it will give you the failed screen. If you didn't do this comment back as there may be something wrong with my original kismet. I tested it earlier and it seems to be fine, so let me know.
Thanks!
