### ISSUE TITLE
Sreynold Vehicle not spawning in Bshively level

### ISSUE THREAD

**Issue by sreynold** [RinglingGameArt/2014-Racing-Game#721]
My vehicle doesn't spawn in Britney's level. I tried with Alec and Andy's cars and both of their cars spawn. 
@bshively

**Comment by egingric** [comment]
Assigning to correct person...

**Comment by bshively** [comment]
I checked through all the cars and Sarah's, Walker's, and Kat's cars are the only one's not spawning. Kat said her car is not spawning because she hasn't finished rigging it yet, but I'm not sure what's causing the other two to not work. I have the most recent Spawn Vehicle kismet code, and both of their cars are hooked up in the kismet. Any idea what else could be causing it?

**Comment by egingric** [comment]
Go into the actor factory's properties and make sure their vehicles are
listed in there. Compare it to the other actor factories that are working.
There is a drop down list of vehicles in the actor factory, so it should be
relatively straightforward.

Regards,
-Eric

**Comment by bshively** [comment]
Turned out their cars were the only ones set to None instead of their car in the drop down menu of the actor factory. I selected their cars in the menus and tested it a couple times and it works now. :)
